### ISSUE TITLE
Autosaves are always in binary format

### ISSUE THREAD

**Issue by DarsFabian** [Adiack06/Vic3GdpGrapher#4]
Autosaves are not in plain-text format despite changing the settings in the launcher. We have to melt down the file.
Some clues on how to do it [here](https://github.com/rakaly/librakaly/blob/master/src/melter.rs).

**Comment by Adiack06** [comment]
I haved moved over to using the binary melter this has solved the problem.
Binary melter thanks to https://github.com/rakaly/cli

**Comment by Adiack06** [comment]
I haved moved over to using the binary melter this has solved the problem.
Binary melter thanks to https://github.com/rakaly/cli
